spring.application.name=LoggingFramework
server.port=8080
#server.address=0.0.0.0


#==== Postgre SQL ====
spring.datasource.url=jdbc:postgresql://localhost:5432/logger_db
spring.datasource.username=postgres
spring.datasource.password=your_new_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Mongo =====
spring.data.mongodb.uri=mongodb://localhost:27017/Logger_DB


# ====== GitHub =====
spring.security.oauth2.client.registration.github.client-id=Ov23liHgaCfCCNZF8BmB
spring.security.oauth2.client.registration.github.client-secret=b45dc9208d1ae1d7d6501e59e3eaf1d6dd047fb3
spring.security.oauth2.client.registration.github.scope=repo,read:user
